# Generated by Django 2.2.6 on 2019-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allot_tg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('have_class', models.CharField(max_length=15)),
                ('tg_email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=260)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
