# Generated by Django 2.2.6 on 2019-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_allot_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_auth',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=60),
            preserve_default=False,
        ),
    ]
