# Generated by Django 2.2.6 on 2019-10-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_admin_auth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_auth',
            name='password',
            field=models.CharField(max_length=260),
        ),
    ]
