# Generated by Django 2.2.6 on 2019-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20191011_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allot_tg',
            name='id',
        ),
        migrations.AlterField(
            model_name='allot_tg',
            name='have_class',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
