# Generated by Django 2.2.6 on 2019-10-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_auto_20191011_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='semister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('class_name', models.CharField(max_length=15)),
                ('subjects', models.CharField(max_length=150)),
            ],
        ),
    ]
