# Generated by Django 2.2.6 on 2019-10-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_image',
            new_name='profile_Image',
        ),
    ]
